# Generated by Django 3.2 on 2022-08-11 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('longitude', models.CharField(default='0', max_length=20, verbose_name='Долгота')),
                ('latitude', models.CharField(default='0', max_length=20, verbose_name='Широта')),
                ('time_refreshed', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 8, 8, 5, 844631, tzinfo=utc), verbose_name='Время последнего обновления')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
    ]
