# Generated by Django 3.2 on 2022-07-28 15:44

from django.db import migrations


def fill_orderelement_price(apps, schema_editor):
    OrderElement = apps.get_model('foodcartapp', 'OrderElement')
    for orderelement in OrderElement.objects.all().iterator(chunk_size=200):
        orderelement.price = orderelement.product.price
        orderelement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20220728_1839'),
    ]

    operations = [
        migrations.RunPython(fill_orderelement_price),
    ]