# Generated by Django 3.2 on 2022-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220728_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unhandled', 'Необработанный'), ('Preparing', 'Готовится'), ('Delivering', 'Доставляется'), ('Finished', 'Завершенный')], db_index=True, default='Unhandled', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
