# Generated by Django 3.2 on 2022-08-10 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220728_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='produced_at',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Приготовить в ресторане'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 11, 48, 57, 158419, tzinfo=utc), verbose_name='Время создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн'), ('cash', 'Наличными')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
