# Generated by Django 3.2 on 2022-08-15 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220815_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='produced_at',
            new_name='assigned_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 5, 57, 43, 627299, tzinfo=utc), verbose_name='Время создания заказа'),
        ),
    ]
